import 'dart:convert';

import 'package:firebase_auth/firebase_auth.dart';
import 'package:http/http.dart' as http;
import 'package:image_picker/image_picker.dart';
import 'package:utilityhub/config/api.dart';

import '../models/giftcard_trade.dart';

class GiftCardTradeService {
  final FirebaseAuth _auth = FirebaseAuth.instance;

  Future<String> _token() async {
    final user = _auth.currentUser;

    if (user == null) {
      throw Exception('Please sign in before trading a gift card.');
    }

    final token = await user.getIdToken();

    if (token == null || token.trim().isEmpty) {
      throw Exception('Unable to authenticate your account.');
    }

    return token;
  }

  Uri _uri(String path) {
    return Uri.parse(ApiConfig.api(path));
  }

  Future<Map<String, dynamic>> getRateCalculatorData() async {
    final token = await _token();

    final response = await http.get(
      _uri('/api/prestmit/sell/rates'),
      headers: {'Accept': 'application/json', 'Authorization': 'Bearer $token'},
    );

    return _decodeResponse(response);
  }

  Future<Map<String, dynamic>> getPayoutMethods() async {
    final token = await _token();

    final response = await http.get(
      _uri('/api/prestmit/sell/payout-methods'),
      headers: {'Accept': 'application/json', 'Authorization': 'Bearer $token'},
    );

    return _decodeResponse(response);
  }

  Future<GiftCardTrade> submitTrade({
    required String giftcardId,
    required String brand,
    required String country,
    required String cardType,
    required String amount,
    required String rate,
    required String expectedPayout,
    required String payoutMethod,
    String? comments,
    List<XFile> images = const [],
  }) async {
    final token = await _token();

    final request = http.MultipartRequest(
      'POST',
      _uri('/api/prestmit/sell/create'),
    );

    request.headers.addAll({
      'Accept': 'application/json',
      'Authorization': 'Bearer $token',
    });

    request.fields['giftcard_id'] = giftcardId;

    request.fields['amount'] = amount;

    request.fields['payoutMethod'] = payoutMethod;

    request.fields['brand'] = brand;

    request.fields['country'] = country;

    request.fields['cardType'] = cardType;

    request.fields['rate'] = rate;

    request.fields['expectedPayout'] = expectedPayout;

    final trimmedComments = comments?.trim();

    if (trimmedComments != null && trimmedComments.isNotEmpty) {
      request.fields['comments'] = trimmedComments;
    }

    /**
     * Unique reference generated by GiftPay.
     *
     * This lets the backend/provider associate
     * the trade with this GiftPay submission.
     */
    request.fields['uniqueIdentifier'] =
        'giftpay-${DateTime.now().millisecondsSinceEpoch}';

    for (final image in images) {
      final bytes = await image.readAsBytes();

      final filename = image.name.isNotEmpty
          ? image.name
          : 'giftcard_${DateTime.now().millisecondsSinceEpoch}.jpg';

      final contentType = _contentType(filename);

      request.files.add(
        http.MultipartFile.fromBytes(
          'attachments[]',
          bytes,
          filename: filename,
          contentType: contentType,
        ),
      );
    }

    final streamedResponse = await request.send();

    final response = await http.Response.fromStream(streamedResponse);

    final body = _decodeResponse(response);

    final transaction = body['transaction'];

    if (transaction is! Map) {
      throw Exception('The server did not return a valid sell transaction.');
    }

    return GiftCardTrade.fromMap({
      'id': transaction['id'],
      'providerReference': transaction['reference'],
      'brand': brand,
      'country': country,
      'cardType': cardType,
      'amount': transaction['amount'] ?? amount,
      'rate': transaction['rate'] ?? rate,
      'valueInNaira': transaction['expectedPayout'] ?? expectedPayout,
      'images': const [],
      'status': transaction['status'] ?? 'PENDING',
      'providerStatus': transaction['providerStatus'] ?? 'PENDING',
      'payoutMethod': transaction['payoutMethod'] ?? payoutMethod,
      'comments': comments,
      'createdAt': transaction['createdAt'] ?? DateTime.now().toIso8601String(),
    });
  }

  Future<List<GiftCardTrade>> getHistory() async {
    final token = await _token();

    final response = await http.get(
      _uri('/api/prestmit/sell/history'),
      headers: {'Accept': 'application/json', 'Authorization': 'Bearer $token'},
    );

    final body = _decodeResponse(response);

    final raw = body['transactions'];

    if (raw is! List) {
      return <GiftCardTrade>[];
    }

    return raw
        .whereType<Map>()
        .map((item) => GiftCardTrade.fromMap(Map<String, dynamic>.from(item)))
        .toList();
  }

  Future<GiftCardTrade> getTransaction(String reference) async {
    final token = await _token();

    final response = await http.get(
      _uri('/api/prestmit/sell/$reference'),
      headers: {'Accept': 'application/json', 'Authorization': 'Bearer $token'},
    );

    final body = _decodeResponse(response);

    final transaction = body['transaction'];

    if (transaction is! Map) {
      throw Exception('Transaction information was not returned.');
    }

    return GiftCardTrade.fromMap(Map<String, dynamic>.from(transaction));
  }

  Future<GiftCardTrade> requeryTransaction(String reference) async {
    final token = await _token();

    final response = await http.post(
      _uri('/api/prestmit/sell/requery/$reference'),
      headers: {'Accept': 'application/json', 'Authorization': 'Bearer $token'},
    );

    final body = _decodeResponse(response);

    final result = body['result'];

    final transaction = await getTransaction(reference);

    if (result is Map) {
      return transaction;
    }

    return transaction;
  }

  Map<String, dynamic> _decodeResponse(http.Response response) {
    dynamic decoded;

    try {
      decoded = jsonDecode(response.body);
    } catch (_) {
      throw Exception('The server returned an invalid response.');
    }

    if (decoded is! Map) {
      throw Exception('The server returned an invalid response.');
    }

    final body = Map<String, dynamic>.from(decoded);

    if (response.statusCode < 200 ||
        response.statusCode >= 300 ||
        body['status'] == false) {
      final message = body['message']?.toString();

      throw Exception(
        message?.isNotEmpty == true
            ? message!
            : 'Gift card request failed (${response.statusCode}).',
      );
    }

    return body;
  }

  http.MediaType _contentType(String filename) {
    final lower = filename.toLowerCase();

    if (lower.endsWith('.png')) {
      return http.MediaType('image', 'png');
    }

    return http.MediaType('image', 'jpeg');
  }
}
