// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgwt4qzrrSIAbsdb2ZMpXNgrzYgiiwhjw',
    appId: '1:137797292697:web:74693c5ecaad3052b05e08',
    messagingSenderId: '137797292697',
    projectId: 'utilityhub-97d26',
    authDomain: 'utilityhub-97d26.firebaseapp.com',
    storageBucket: 'utilityhub-97d26.firebasestorage.app',
    measurementId: 'G-3068EFR0TE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEaWHlLjuvUngFhiRYY1YlhptMCOsd3KY',
    appId: '1:137797292697:android:d319cf99dbbcd1c1b05e08',
    messagingSenderId: '137797292697',
    projectId: 'utilityhub-97d26',
    storageBucket: 'utilityhub-97d26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt4IMxHy8Kfre4kEMg245tB8puTU-RAz4',
    appId: '1:137797292697:ios:f3888f80e44bc4a2b05e08',
    messagingSenderId: '137797292697',
    projectId: 'utilityhub-97d26',
    storageBucket: 'utilityhub-97d26.firebasestorage.app',
    iosBundleId: 'com.example.utilityhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt4IMxHy8Kfre4kEMg245tB8puTU-RAz4',
    appId: '1:137797292697:ios:f3888f80e44bc4a2b05e08',
    messagingSenderId: '137797292697',
    projectId: 'utilityhub-97d26',
    storageBucket: 'utilityhub-97d26.firebasestorage.app',
    iosBundleId: 'com.example.utilityhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgwt4qzrrSIAbsdb2ZMpXNgrzYgiiwhjw',
    appId: '1:137797292697:web:67fec6effae56c9ab05e08',
    messagingSenderId: '137797292697',
    projectId: 'utilityhub-97d26',
    authDomain: 'utilityhub-97d26.firebaseapp.com',
    storageBucket: 'utilityhub-97d26.firebasestorage.app',
    measurementId: 'G-9STL30C5YX',
  );
}
